quarkus:
  application:
    name: voting-app
  shutdown:
    timeout: 5S

"%dev":
  quarkus:
    http:
      port: 8082
    opentelemetry:
      enabled: false

"%prod":
  quarkus:
    log:
      handler:
        gelf:
          enabled: true
          additional-field:
            "app":
              value: ${quarkus.application.name}
          include-full-mdc: true
      console:
        format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    opentelemetry:
      enabled: true
